name: SudoScan Develop CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'develop'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'release/**'
      - 'support/**'
jobs:
  gradle_dev_build:
    name: Gradle Dev Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setting up JAVA
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

#      - name: Running gradle task
#        uses: gradle/gradle-build-action@v2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          gradle-version: wrapper
#          arguments: -Pweb-cli clean assembleWebApp

      - name: Execute Gradle build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sudoscan_dev_web_jars
          path: build/*.jar
